name: ci-golang-workflow
on: [push] #toda vez que eu der um push neste repo esse processo vai rodar
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #pega os nossos arquivos e baixa numa máquina ubuntu
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test
      - run: go run math.go

